# Generated by Django 3.2.12 on 2022-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
