# Generated by Django 3.2.12 on 2022-02-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_alter_pontos_turisticos_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
