# Generated by Django 3.2.12 on 2022-02-13 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('core', '0005_pontos_turisticos_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='localizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizacao.localizacao'),
            preserve_default=False,
        ),
    ]
