# Generated by Django 3.2.12 on 2022-03-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pontos_turisticos_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
